name: PR Target Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

concurrency:
  group: "pr-target-check"
  cancel-in-progress: false
  
jobs:
  is-using-correct-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.base_ref }} == "stable" ] && [ ${{ github.head_ref }} != "development" ]; then
            echo "Merge requests to the stable branch are only allowed from the development branch."
            exit 1
          fi
